apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    {{- toYaml .Values.servicePorts | nindent 2 }}
  selector:
    app: {{ .Values.appName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      securityContext:
        runAsUser: {{ .Values.global.runAsUser }}
        runAsGroup: {{ .Values.global.runAsGroup }}
      volumes:
        # Mount config files from secrets
        - name: secrets
          projected:
            sources:
              - secret:
                  name: {{ .Values.global.murfeyMachineConfigSecretName }}
              - secret:
                  name: {{ .Values.global.murfeySecurityConfigSecretName }}
              - secret:
                  name: {{ .Values.global.ispybSecretName }}
              - secret:
                  name: {{ .Values.global.murfeyDBSecretName }}
              - secret:
                  name: {{ .Values.global.rmqSecretName }}
        # Mount data directories
        {{- toYaml .Values.extraVolumes | nindent 8 }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          securityContext:
            privileged: false
          volumeMounts:
            # Mount config files
            - name: secrets
              mountPath: /murfey/config
              readOnly: true
            # Mount data directories
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          env:
            - name: MURFEY_MACHINE_CONFIGURATION
              value: "/murfey/config/{{ .Values.global.murfeyMachineConfigFileName }}"
            - name: MURFEY_SECURITY_CONFIGURATION
              value: "/murfey/config/{{ .Values.global.murfeySecurityConfigFileName }}"
            - name: ISPYB_CREDENTIALS
              value: "/murfey/config/{{ .Values.global.ispybFileName }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
