"""
Functions shared by the FIB workflows
"""

import math
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

import numpy as np
import PIL.Image

from murfey.util.db import ImagingSite
from murfey.util.fib import get_slot_number
from murfey.util.models import FIBImageMetadata


def parse_image_metadata(
    file: Path,
    rotation_offset: float,
):
    """
    Helper function that goes through a FIB image and extracts the metadata of
    interest from it.

    The metadata is stored in different formats (e.g. XML, INI, ...) under different
    keys, with these key names differing depending on the image file format. The
    metadata extraction logic can eventually be extended to thoroughly search the
    image's keys to look for metadata if the initial key fails.

    Currently, this function works for the following images generated by the
    AutoTEM and Maps software packages:
    1. Electron snapshot TIFFs (Maps)
    2. Lamella evaluation images (AutoTEM)
    """

    # Open image and load metadata
    img = PIL.Image.open(file)
    metadata_format = ""
    match file.suffix:
        # For PNGs, metadata is stored under the 'text' attribute
        case ".png":
            tags = dict(img.text)
            # XML metadata is stored as a string under 'Metadata'
            if tag_contents := tags.get("Metadata"):
                metadata_format = "xml"
            else:
                raise ValueError(
                    "Could not find metadata under the expected key 'Metadata'"
                )
        # For TIFFs, it's stored under the 'tag_v2' attribute
        case ".tif" | ".tiff":
            tags = dict(img.tag_v2)
            # XML metadata is stored as a string under '34683'
            if tag_contents := tags.get(34683):
                metadata_format = "xml"
            else:
                raise ValueError(
                    "Could not find metadata under the expected key '34683'"
                )
        case _:
            raise NotImplementedError(f"Unsupported image type {file.suffix!r}")

    # Parse and extract metadata based on the known format
    extracted: dict[str, Any] = {}
    match metadata_format:
        case "xml":
            # XML metadata is written as a single string and needs to be parsed
            xml_metadata = ET.fromstring(tag_contents)

            # Extract key values from metadata
            extracted = {
                key: node.text
                if (node := xml_metadata.find(node_path)) is not None
                else None
                for key, node_path in (
                    ("voltage", ".//Optics/AccelerationVoltage"),
                    ("shift_x", ".//Optics/BeamShift/X"),
                    ("shift_y", ".//Optics/BeamShift/Y"),
                    ("len_x", ".//Optics/ScanFieldOfView/X"),
                    ("len_y", ".//Optics/ScanFieldOfView/Y"),
                    ("pos_x", ".//StageSettings/StagePosition/X"),
                    ("pos_y", ".//StageSettings/StagePosition/Y"),
                    ("pos_z", ".//StageSettings/StagePosition/Z"),
                    # Angles are in radians
                    ("rotation", ".//StageSettings/StagePosition/Rotation"),
                    ("tilt_alpha", ".//StageSettings/StagePosition/Tilt/Alpha"),
                    ("tilt_beta", ".//StageSettings/StagePosition/Tilt/Beta"),
                    ("pixels_x", ".//BinaryResult/ImageSize/X"),
                    ("pixels_y", ".//BinaryResult/ImageSize/Y"),
                    ("pixel_size_x", ".//BinaryResult/PixelSize/X"),
                    ("pixel_size_y", ".//BinaryResult/PixelSize/Y"),
                )
            }
            # Calculate the slot number
            extracted["slot_number"] = get_slot_number(
                x=float(extracted["pos_x"]),
                y=float(extracted["pos_y"]),
                rotation=math.degrees(
                    float(extracted["rotation"])
                ),  # Convert to degrees
                rotation_offset=rotation_offset,
            )
        case _:
            raise NotImplementedError(
                f"Unsupported metadata format {metadata_format!r}"
            )
    return extracted


def populate_fib_imaging_site_entry(
    imaging_site: ImagingSite,
    metadata: FIBImageMetadata,
):
    imaging_site.image_path = str(metadata.file)
    imaging_site.pos_x = metadata.pos_x
    imaging_site.pos_y = metadata.pos_y
    imaging_site.pos_z = metadata.pos_z
    imaging_site.rotation = float(np.rad2deg(metadata.rotation))
    imaging_site.tilt_alpha = float(np.rad2deg(metadata.tilt_alpha))
    imaging_site.tilt_beta = float(np.rad2deg(metadata.tilt_beta))
    imaging_site.len_x = metadata.len_x
    imaging_site.len_y = metadata.len_y
    imaging_site.image_pixels_x = metadata.pixels_x
    imaging_site.image_pixels_y = metadata.pixels_y
    imaging_site.image_pixel_size = metadata.pixel_size

    if metadata.thumbnail_path is not None:
        scale = 512 / (max(metadata.pixels_x, metadata.pixels_y) or 1)
        imaging_site.thumbnail_path = str(metadata.thumbnail_path)
        imaging_site.thumbnail_pixels_x = int(round(metadata.pixels_x * scale)) or 1
        imaging_site.thumbnail_pixels_y = int(round(metadata.pixels_y * scale)) or 1
        imaging_site.thumbnail_pixel_size = metadata.pixel_size / scale

    return imaging_site
