"""
Functions shared by the FIB workflows
"""

from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import TYPE_CHECKING, Any

import numpy as np
import PIL.Image
from sqlmodel import Session as SQLModelSession, select

import murfey.util.db as MurfeyDB
from murfey.util.fib import get_slot_number, number_from_name
from murfey.util.models import FIBImageMetadata, GridSquareParameters

if TYPE_CHECKING:
    from murfey.server.ispyb import TransportManager


def parse_image_metadata(
    file: Path,
    rotation_offset: float,
):
    """
    Helper function that goes through a FIB image and extracts the metadata of
    interest from it.

    The metadata is stored in different formats (e.g. XML, INI, ...) under different
    keys, with these key names differing depending on the image file format. The
    metadata extraction logic can eventually be extended to thoroughly search the
    image's keys to look for metadata if the initial key fails.

    Currently, this function works for the following images generated by the
    AutoTEM and Maps software packages:
    1. Electron snapshot TIFFs (Maps)
    2. Lamella evaluation images (AutoTEM)
    """

    # Open image and load metadata
    img = PIL.Image.open(file)
    metadata_format = ""
    match file.suffix:
        # For PNGs, metadata is stored under the 'text' attribute
        case ".png":
            tags = dict(img.text)
            # XML metadata is stored as a string under 'Metadata'
            if tag_contents := tags.get("Metadata"):
                metadata_format = "xml"
            else:
                raise ValueError(
                    "Could not find metadata under the expected key 'Metadata'"
                )
        # For TIFFs, it's stored under the 'tag_v2' attribute
        case ".tif" | ".tiff":
            tags = dict(img.tag_v2)
            # XML metadata is stored as a string under '34683'
            if tag_contents := tags.get(34683):
                metadata_format = "xml"
            else:
                raise ValueError(
                    "Could not find metadata under the expected key '34683'"
                )
        case _:
            raise NotImplementedError(f"Unsupported image type {file.suffix!r}")

    # Parse and extract metadata based on the known format
    extracted: dict[str, Any] = {}
    match metadata_format:
        case "xml":
            # XML metadata is written as a single string and needs to be parsed
            xml_metadata = ET.fromstring(tag_contents)

            # Extract key values from metadata
            extracted = {
                key: node.text
                if (node := xml_metadata.find(node_path)) is not None
                else None
                for key, node_path in (
                    ("voltage", ".//Optics/AccelerationVoltage"),
                    ("shift_x", ".//Optics/BeamShift/X"),
                    ("shift_y", ".//Optics/BeamShift/Y"),
                    ("len_x", ".//Optics/ScanFieldOfView/X"),
                    ("len_y", ".//Optics/ScanFieldOfView/Y"),
                    ("pos_x", ".//StageSettings/StagePosition/X"),
                    ("pos_y", ".//StageSettings/StagePosition/Y"),
                    ("pos_z", ".//StageSettings/StagePosition/Z"),
                    # Angles are in radians
                    ("rotation", ".//StageSettings/StagePosition/Rotation"),
                    ("tilt_alpha", ".//StageSettings/StagePosition/Tilt/Alpha"),
                    ("tilt_beta", ".//StageSettings/StagePosition/Tilt/Beta"),
                    ("pixels_x", ".//BinaryResult/ImageSize/X"),
                    ("pixels_y", ".//BinaryResult/ImageSize/Y"),
                    ("pixel_size_x", ".//BinaryResult/PixelSize/X"),
                    ("pixel_size_y", ".//BinaryResult/PixelSize/Y"),
                )
            }
            # Calculate the slot number
            extracted["slot_number"] = get_slot_number(
                x=float(extracted["pos_x"]),
                y=float(extracted["pos_y"]),
                rotation=math.degrees(
                    float(extracted["rotation"])
                ),  # Convert to degrees
                rotation_offset=rotation_offset,
            )
            # Determine the lamella number
            try:
                parts = file.parts
                site_idx = parts.index("Sites") + 1
                extracted["lamella_number"] = number_from_name(parts[site_idx])
            except ValueError:
                extracted["lamella_number"] = None
        case _:
            raise NotImplementedError(
                f"Unsupported metadata format {metadata_format!r}"
            )
    return extracted


def populate_fib_imaging_site_entry(
    imaging_site: MurfeyDB.ImagingSite,
    metadata: FIBImageMetadata,
):
    imaging_site.image_path = str(metadata.file)
    imaging_site.pos_x = metadata.pos_x
    imaging_site.pos_y = metadata.pos_y
    imaging_site.pos_z = metadata.pos_z
    imaging_site.rotation = float(np.rad2deg(metadata.rotation))
    imaging_site.tilt_alpha = float(np.rad2deg(metadata.tilt_alpha))
    imaging_site.tilt_beta = float(np.rad2deg(metadata.tilt_beta))
    imaging_site.len_x = metadata.len_x
    imaging_site.len_y = metadata.len_y
    imaging_site.image_pixels_x = metadata.pixels_x
    imaging_site.image_pixels_y = metadata.pixels_y
    imaging_site.image_pixel_size = metadata.pixel_size

    if metadata.thumbnail_path is not None:
        scale = 512 / (max(metadata.pixels_x, metadata.pixels_y) or 1)
        imaging_site.thumbnail_path = str(metadata.thumbnail_path)
        imaging_site.thumbnail_pixels_x = int(round(metadata.pixels_x * scale)) or 1
        imaging_site.thumbnail_pixels_y = int(round(metadata.pixels_y * scale)) or 1
        imaging_site.thumbnail_pixel_size = metadata.pixel_size / scale

    return imaging_site


def populate_fib_grid_square_entry(
    session_id: int,
    dcg_name: str,
    atlas: MurfeyDB.ImagingSite,
    lamella: MurfeyDB.ImagingSite,
    lamella_number: int,
    transport_object: TransportManager,
    murfey_db: SQLModelSession,
):
    """
    Helper function to create/update an ISPyB GridSquare entry for a FIB lamella
    image so that its coordinates on the parent atlas image are up-to-date. Returns
    the corresponding Murfey GridSquare entry, which can then be added and committed
    to the database in the parent function.
    """
    # Check if the atlas has the required values for the GridSquare registration
    if not (
        atlas.pos_x is not None
        and atlas.pos_y is not None
        and atlas.pos_z is not None
        and atlas.rotation is not None
        and atlas.tilt_alpha is not None
        and atlas.len_x is not None
        and atlas.len_y is not None
        and atlas.thumbnail_pixels_x is not None
        and atlas.thumbnail_pixels_y is not None
    ):
        raise ValueError(
            f"Atlas {atlas.image_path} missing one or more required values: \n"
            "  'pos_x'\n"
            "  'pos_y'\n"
            "  'pos_z'\n"
            "  'rotation'\n"
            "  'tilt_alpha'\n"
            "  'len_x'\n"
            "  'len_y'\n"
            "  'thumbnail_pixels_x'\n"
            "  'thumbnail_pixels_x'"
        )
    atlas_x1 = atlas.pos_x + (atlas.len_x / 2)
    atlas_y0 = atlas.pos_y - (atlas.len_y / 2)

    # Check that the lamella ImagingSite entry has the required values
    if not (
        lamella.pos_x is not None
        and lamella.pos_y is not None
        and lamella.pos_z is not None
        and lamella.rotation is not None
        and lamella.tilt_alpha is not None
        and lamella.len_x is not None
        and lamella.len_y is not None
    ):
        raise ValueError(
            f"ImagingSite for {lamella.image_path} missing one or more required values: \n"
            "  'pos_x'\n"
            "  'pos_y'\n"
            "  'pos_z'\n"
            "  'rotation'\n"
            "  'tilt_alpha'\n"
            "  'len_x'\n"
            "  'len_y'"
        )

    # Transform the imaging site coordinates into the atlas' frame of reference
    # NOTE: This will require further investigation and tweaking, given the
    # many axes and centres of rotation present in the FIB stage system.
    # We start with a simple 2D rotation for now, and will adjust it as we observe
    # the alignment accuracy
    theta = math.radians(lamella.rotation - atlas.rotation)
    sin = math.sin(theta)
    cos = math.cos(theta)
    x_transformed = (lamella.pos_x * cos) - (lamella.pos_y * sin)
    y_transformed = (lamella.pos_x * sin) + (lamella.pos_y * cos)

    # Find the pixel coordinates of the image on the atlas
    # NOTE: On the atlas image, positive directions are LEFT (x) and DOWN (y)
    x_mid_px = int(
        round((atlas_x1 - x_transformed) / atlas.len_x * atlas.thumbnail_pixels_x) or 1
    )
    y_mid_px = int(
        round((y_transformed - atlas_y0) / atlas.len_y * atlas.thumbnail_pixels_y) or 1
    )

    # Find the pixel width and height of the lamella image on the atlas
    width_scaled = int(
        round((lamella.len_x / atlas.len_x) * atlas.thumbnail_pixels_x) or 1
    )
    height_scaled = int(
        round((lamella.len_y / atlas.len_y) * atlas.thumbnail_pixels_y) or 1
    )

    # Populate GridSquareParameters model
    grid_square_params = GridSquareParameters(
        tag=dcg_name,
        x_location=x_transformed,
        x_location_scaled=x_mid_px,
        y_location=y_transformed,
        y_location_scaled=y_mid_px,
        readout_area_x=lamella.image_pixels_x,
        readout_area_y=lamella.image_pixels_y,
        thumbnail_size_x=lamella.thumbnail_pixels_x,
        thumbnail_size_y=lamella.thumbnail_pixels_y,
        width=lamella.image_pixels_x,
        width_scaled=width_scaled,
        height=lamella.image_pixels_y,
        height_scaled=height_scaled,
        x_stage_position=x_transformed,
        y_stage_position=y_transformed,
        pixel_size=lamella.image_pixel_size,
        image=lamella.thumbnail_path,
    )

    # Register or update the grid square entry as required
    grid_square_entry = murfey_db.exec(
        select(MurfeyDB.GridSquare)
        .where(MurfeyDB.GridSquare.name == lamella_number)
        .where(MurfeyDB.GridSquare.session_id == session_id)
        .where(MurfeyDB.GridSquare.tag == grid_square_params.tag)
    ).one_or_none()
    if grid_square_entry is not None:
        # Update existing grid square entry on Murfey
        grid_square_entry.x_location = grid_square_params.x_location
        grid_square_entry.y_location = grid_square_params.y_location
        grid_square_entry.x_stage_position = grid_square_params.x_stage_position
        grid_square_entry.y_stage_position = grid_square_params.y_stage_position
        grid_square_entry.readout_area_x = grid_square_params.readout_area_x
        grid_square_entry.readout_area_y = grid_square_params.readout_area_y
        grid_square_entry.thumbnail_size_x = grid_square_params.thumbnail_size_x
        grid_square_entry.thumbnail_size_y = grid_square_params.thumbnail_size_y
        grid_square_entry.pixel_size = grid_square_params.pixel_size
        grid_square_entry.image = grid_square_params.image

        # Update existing entry on ISPyB
        transport_object.do_update_grid_square(
            grid_square_id=grid_square_entry.id,
            grid_square_parameters=grid_square_params,
        )
    else:
        # Look up data collection group for current series
        dcg_entry = murfey_db.exec(
            select(MurfeyDB.DataCollectionGroup)
            .where(MurfeyDB.DataCollectionGroup.session_id == session_id)
            .where(MurfeyDB.DataCollectionGroup.tag == grid_square_params.tag)
        ).one()
        # Register to ISPyB
        grid_square_ispyb_result = transport_object.do_insert_grid_square(
            atlas_id=dcg_entry.atlas_id,
            grid_square_id=lamella_number,
            grid_square_parameters=grid_square_params,
        )
        # Create matching record in Murfey
        grid_square_entry = MurfeyDB.GridSquare(
            id=grid_square_ispyb_result.get("return_value", None),
            name=lamella_number,
            session_id=session_id,
            tag=grid_square_params.tag,
            x_location=grid_square_params.x_location,
            y_location=grid_square_params.y_location,
            x_stage_position=grid_square_params.x_stage_position,
            y_stage_position=grid_square_params.y_stage_position,
            readout_area_x=grid_square_params.readout_area_x,
            readout_area_y=grid_square_params.readout_area_y,
            thumbnail_size_x=grid_square_params.thumbnail_size_x,
            thumbnail_size_y=grid_square_params.thumbnail_size_y,
            pixel_size=grid_square_params.pixel_size,
            image=grid_square_params.image,
        )

    return grid_square_entry
