[tool.bumpversion]
current_version = "0.13.1"
commit = true
tag = true

[tool.bumpversion.files]
filname = "src/murfey/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[took.bumpversion.files]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
