name: Run tests and publish Python distribution to PyPI

on: [push, pull_request]

env:
  DATABASE_SCHEMA: 4.2.1 # released 2024-08-19
  # Installs from GitHub
  # Versions: https://github.com/DiamondLightSource/ispyb-database/tags
  # Previous version(s):
  # 4.1.0

permissions:
  contents: read

jobs:
  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Syntax validation
        run: |
          python .github/workflows/scripts/syntax-validation.py
      - name: Flake8 validation
        run: |
          pip install flake8
          python .github/workflows/scripts/flake8-validation.py

  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install --disable-pip-version-check collective.checkdocs wheel
      - name: Build python package
        run: |
          set -ex
          python setup.py sdist bdist_wheel
          mkdir -p dist/pypi
          shopt -s extglob
          mv -v dist/!(pypi) dist/pypi
          git archive HEAD | gzip > dist/repo-source.tar.gz
          ls -laR dist
      - name: Download ISPyB DB schema v${{ env.DATABASE_SCHEMA }} for tests
        run: wget -t 3 --waitretry=20 https://github.com/DiamondLightSource/ispyb-database/releases/download/v${{ env.DATABASE_SCHEMA }}/ispyb-database-${{ env.DATABASE_SCHEMA }}.tar.gz -O dist/ispyb-database.tar.gz
      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-distributions
          path: dist/
      - name: Check package description
        run: python setup.py checkdocs

  tests:
    name: Call ci unit tests workflow
    uses: ./.github/workflows/ci.yml
    needs:
      - build
      - static
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
