name: Bump the version

on:
  workflow_dispatch:
    inputs:
      bumpLevel:
        description: "Kind of version bump"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: read

jobs:
  bumpversion:
    name: Bump the package version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install package
        run: |
          set -eux
          pip install --disable-pip-version-check -e "."[cicd,client,server,developer]
      - name: Run bumpversion
        run: |
          bump2version ${{ inputs.bumpLevel }}
          git push origin main
      - name: Get new version and push tag
        run: |
          pip install --disable-pip-version-check -e "."[cicd,client,server,developer]
          VERSION=$(python -c "import murfey; print(murfey.__version__)")
          git push origin v$VERSION
